""" Arithmetic Operator Operation Program"""

num1=int(input("Enter your first number : "))
num2=int(input("Enter your second number : "))
print("-------------------------------")
print(f"{num1} + {num2} = {num1+num2}")
print("-------------------------------")
print(f"{num1} - {num2} = {num1-num2}")
print("-------------------------------")
print(f"{num1} * {num2} = {num1*num2}")
print("-------------------------------")
print(f"{num1} / {num2} = {num1/num2}")
print("-------------------------------")
print(f"{num1} // {num2} = {num1//num2}")
print("-------------------------------")
print(f"{num1} % {num2} = {num1%num2}")
print("-------------------------------")
print(f"{num1} ** {num2} = {num1**num2}")
print("-------------------------------")
print("-------------------------------")
print("Calculation Process Completed ")
